[package]
name = "ddk-rs"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Andrew Walbran <qwandor@google.com>", "Anthony Stange <stange@google.com>"]
description = "Rust DDK for the Zircon kernel"
repository = "https://fuchsia.googlesource.com/ddk-rs/"

[dependencies]
ddk-sys = { path = "ddk-sys" }
fuchsia-zircon = { path = "../fuchsia-zircon" }
