# Copyright 2018 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
[package]
name = "fidl_media"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["rust-fuchsia@fuchsia.com"]
description = "Generated FIDL interface"
repository = "https://fuchsia.googlesource.com/garnet/"

[dependencies]
fidl = "0.1"
fuchsia-zircon = "0.3"
futures = "=0.2.0-alpha"
fuchsia-async = "0.1"
fidl_gfx = "0.1"
fidl_views = "0.1"
fidl_geometry = "0.1"
fidl_component = "0.1"
fidl_scenic_dummy_system = "0.1"
fidl_views_v1 = "0.1"
fidl_mem = "0.1"
fidl_ui = "0.1"
fidl_images = "0.1"
fidl_input = "0.1"
fidl_views_v1_token = "0.1"
