[package]
name = "fidl2_examples"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Taylor Cramer <cramertj@google.com>"]
description = "Generated interface"
repository = "https://fuchsia.googlesource.com/garnet/"

[dependencies]
fidl = "0.1"
fuchsia-zircon = "0.3"
futures = "=0.2.0-alpha"
fuchsia-async = "0.1"

