[package]
name = "ddk_toy"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Andrew Walbran <qwandor@google.com>", "Anthony Stange <stange@google.com>"]
description = "Sample app for interacting with the Rust DDK for the Zircon kernel"
repository = "https://fuchsia.googlesource.com/ddk-rs/"
build = "build.rs"

[lib]
name = "ddk_toy"
crate-type = ["dylib"]

[dependencies]
ddk-rs = { path = "../../../ddk-rs" }
ddk-sys = { path = "../../ddk-sys" }
fuchsia-zircon = { path = "../../../fuchsia-zircon" }

[build-dependencies]
gcc = "0.3"
