name: fxutils
description: Generic fx utilities for fx subcommands written in Dart.
version: 0.0.1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  path: ^1.6.4
  pedantic: ^1.8.0+1

dev_dependencies:
  test: ^1.9.3
