name: codesize

# NOTE: This is used only when actively developing `fx codesize`, or when
# manually running its unit tests by navigating to this directory and
# executing `pub run test .`. It needs to maintained synchronized with
# `.dart_tools/packages_config.json`.
dependencies:
  async:
    path: ../../third_party/dart-pkg/pub/async
  convert:
    path: ../../third_party/dart-pkg/pub/convert
  args:
    path: ../../third_party/dart-pkg/pub/args
  pool:
    path: ../../third_party/dart-pkg/pub/pool
  collection:
    path: ../../third_party/dart-pkg/pub/collection
  csslib:
    path: ../../third_party/dart-pkg/pub/csslib
  stack_trace:
    path: ../../third_party/dart-pkg/pub/stack_trace
  path:
    path: ../../third_party/dart-pkg/pub/path
  file:
    path: ../../third_party/dart-pkg/pub/file
  fixnum:
    path: ../../third_party/dart-pkg/pub/fixnum
  googleapis_auth:
    path: ../../third_party/dart-pkg/pub/googleapis_auth
  gcloud:
    path: ../../third_party/dart-pkg/pub/gcloud
  http:
    path: ../../third_party/dart-pkg/pub/http
  html:
    path: ../../third_party/dart-pkg/pub/html
  io:
    path: ../../third_party/dart-pkg/pub/io
  meta:
    path: ../../third_party/dart-pkg/pub/meta
  googleapis:
    path: ../../third_party/dart-pkg/pub/googleapis
  http_parser:
    path: ../../third_party/dart-pkg/pub/http_parser
  _discoveryapis_commons:
    path: ../../third_party/dart-pkg/pub/_discoveryapis_commons
  crypto:
    path: ../../third_party/dart-pkg/pub/crypto
  string_scanner:
    path: ../../third_party/dart-pkg/pub/string_scanner
  source_span:
    path: ../../third_party/dart-pkg/pub/source_span
  charcode:
    path: ../../third_party/dart-pkg/pub/charcode
  typed_data:
    path: ../../third_party/dart-pkg/pub/typed_data
  term_glyph:
    path: ../../third_party/dart-pkg/pub/term_glyph
  test:
    path: ../../third_party/dart-pkg/pub/test
  vm_service:
    path: ../../third_party/dart-pkg/pub/vm_service
  watcher:
    path: ../../third_party/dart-pkg/pub/watcher
  pedantic:
    path: ../../third_party/dart-pkg/pub/pedantic
  process:
    path: ../../third_party/dart-pkg/pub/process
  protobuf:
    path: ../../third_party/dart-pkg/pub/protobuf
  fxutils:
    path: ../fxutils/lib

dependency_overrides:
  async:
    path: ../../third_party/dart-pkg/pub/async
  convert:
    path: ../../third_party/dart-pkg/pub/convert
  args:
    path: ../../third_party/dart-pkg/pub/args
  pool:
    path: ../../third_party/dart-pkg/pub/pool
  collection:
    path: ../../third_party/dart-pkg/pub/collection
  csslib:
    path: ../../third_party/dart-pkg/pub/csslib
  stack_trace:
    path: ../../third_party/dart-pkg/pub/stack_trace
  path:
    path: ../../third_party/dart-pkg/pub/path
  file:
    path: ../../third_party/dart-pkg/pub/file
  fixnum:
    path: ../../third_party/dart-pkg/pub/fixnum
  googleapis_auth:
    path: ../../third_party/dart-pkg/pub/googleapis_auth
  gcloud:
    path: ../../third_party/dart-pkg/pub/gcloud
  http:
    path: ../../third_party/dart-pkg/pub/http
  html:
    path: ../../third_party/dart-pkg/pub/html
  io:
    path: ../../third_party/dart-pkg/pub/io
  meta:
    path: ../../third_party/dart-pkg/pub/meta
  googleapis:
    path: ../../third_party/dart-pkg/pub/googleapis
  http_parser:
    path: ../../third_party/dart-pkg/pub/http_parser
  _discoveryapis_commons:
    path: ../../third_party/dart-pkg/pub/_discoveryapis_commons
  crypto:
    path: ../../third_party/dart-pkg/pub/crypto
  string_scanner:
    path: ../../third_party/dart-pkg/pub/string_scanner
  source_span:
    path: ../../third_party/dart-pkg/pub/source_span
  charcode:
    path: ../../third_party/dart-pkg/pub/charcode
  typed_data:
    path: ../../third_party/dart-pkg/pub/typed_data
  term_glyph:
    path: ../../third_party/dart-pkg/pub/term_glyph
  test:
    path: ../../third_party/dart-pkg/pub/test
  vm_service:
    path: ../../third_party/dart-pkg/pub/vm_service
  watcher:
    path: ../../third_party/dart-pkg/pub/watcher
  pedantic:
    path: ../../third_party/dart-pkg/pub/pedantic
  process:
    path: ../../third_party/dart-pkg/pub/process
  protobuf:
    path: ../../third_party/dart-pkg/pub/protobuf
  fxutils:
    path: ../fxutils/lib
