[package]
name = "garnet_public_lib_app_fidl"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Rob Tsuk <robtsuk@google.com>"]
description = "Generated interface"
repository = "https://fuchsia.googlesource.com/garnet/"

[dependencies]
fidl = "0.1"
fuchsia-zircon = "0.3"
futures = "=0.2.0-alpha"
garnet_public_lib_app_fidl_service_provider = "0.1"
garnet_public_lib_fsl_fidl = "0.1"
fuchsia-async = "0.1"

