[package]
name = "ddk-sys"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Andrew Walbran <qwandor@google.com>", "Anthony Stange <stange@google.com>"]
description = "Low-level Rust DDK for the Zircon kernel"
repository = "https://fuchsia.googlesource.com/ddk-rs/"

[dependencies]
bitflags = "0.7.0"
fuchsia-zircon = { path = "../../fuchsia-zircon" }
