[package]
name = "ddk-sys"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Andrew Walbran <qwandor@google.com>", "Anthony Stange <stange@google.com>"]
description = "Low-level Rust DDK for the Zircon kernel"
repository = "https://fuchsia.googlesource.com/ddk-rs/"

[dependencies]
zircon-sys = { path = "../../fuchsia-zircon/fuchsia-zircon-sys", version = "0.2.0" }
