# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[package]
name = "wlanstack2"
version = "0.1.0"
license = "BSD-3-Clause"

[dependencies]
failure = "0.1"
fidl = "0.1"
fuchsia-app = "0.1"
fuchsia-async = "0.1"
fuchsia-vfs-watcher = "0.1"
fuchsia-wlan-dev = "0.1"
fuchsia-zircon = "0.3"
futures = "=0.2.0-alpha"
# garnet_lib_wlan_fidl = "0.1"
# garnet_lib_wlan_fidl_service = "0.1"
log = "0.3"
parking_lot = "0.4"
wlan-sme = "0.1"
