[package]
name = "fdio"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Tim Kilbourn <tkilbourn@google.com>"]
description = "Rust bindings for Zircon fdio"
repository = "https://fuchsia.googlesource.com/fdio-rs/"

[dependencies]
fuchsia-zircon = { path = "../fuchsia-zircon", version = "0.3" }
fuchsia-zircon-sys = { path = "../fuchsia-zircon/fuchsia-zircon-sys", version = "0.3" }
