[package]
name = "mxio"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Tim Kilbourn <tkilbourn@google.com>"]
description = "Rust bindings for Magenta mxio"
repository = "https://fuchsia.googlesource.com/mxio-rs/"

[dependencies]
magenta = { path = "../magenta-rs", version = "0.1" }

magenta-sys = { path = "../magenta-rs/magenta-sys", version = "0.1" }
