[package]
name = "fdio"
version = "0.2.0"
license = "BSD-3-Clause"
authors = ["Tim Kilbourn <tkilbourn@google.com>"]
description = "Rust bindings for Zircon fdio"
repository = "https://fuchsia.googlesource.com/fdio-rs/"

[dependencies]
fuchsia-zircon = "0.3"
fuchsia-zircon-sys = "0.3"
bytes = "0.4"