[package]
name = "garnet_public_lib_mdns_fidl"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Craig Tiller <ctiller@google.com>"]
description = "Generated interface"
repository = "https://fuchsia.googlesource.com/garnet/"

[dependencies]
fidl = "0.1"
fuchsia-zircon = "0.3"
futures = "0.1.15"
tokio-core = "0.1"
tokio-fuchsia = "0.1"
garnet_public_lib_app_fidl = "0.1"
garnet_public_lib_netstack_fidl_net_address = "0.1"
