# Copyright 2018 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[package]
name = "fuchsia-zircon"
version = "0.3.3"
license-file = "LICENSE"
authors = ["rust-fuchsia@fuchsia.com"]
description = "Rust crate for Fuchsia OS"
repository = "https://fuchsia.googlesource.com"
edition = "2018"

[dependencies]
failure = "0.1.1"
bitflags = "1"

[dependencies.fuchsia-zircon-sys]
path = "fuchsia-zircon-sys"
version = "0.3.3"
edition = "2018"

[dependencies.fuchsia-zircon-status]
path = "fuchsia-zircon-status"
version = "0.1"
edition = "2018"
