# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
name: internationalization
description: The internationalization library for Fuchsia.

environment:
  # Future is exported since SDK 2.1
  sdk: '>=2.12.0-0 <3.0.0'

flutter:

dependencies:
  # Needed for the ARB extraction scripts until this is fully automated.
  intl_translation: ^0.17.2

