[package]
name = "audio_player_rust"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Adam MacBeth <amacbeth@google.com>"]
description = "Rust Audio Player"
repository = "https://fuchsia.googlesource.com/garnet/"

[dependencies]
failure = "0.1"
fdio = "0.2"
fidl = "0.1"
fidl_media_player = "0.1"
fuchsia-app = "0.1"
fuchsia-async = "0.1"
fuchsia-zircon = "0.3"
futures = "=0.2.0-alpha"
mxruntime = "0.1"
mxruntime-sys = "0.1"
structopt = "0.2"
url = "1.7.0"